version: '3.0'
services:
  game-service:
    image: "registry.gitlab.com/pokesync/game-service:latest"
    environment:
      POKESYNC_HOST: "0.0.0.0"
      POKESYNC_PORT: 23192
      POKESYNC_REDIS_HOST: "redis"
      POKESYNC_REDIS_PORT: 6379
    ports:
      - "23192:23192"
    depends_on:
      - "redis"
      - "db"
  db:
    image: "postgres:latest"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  redis:
    image: "redis:latest"
    ports:
    - "6379:6379"