version: '3.0'
services:
  game-service:
    build: .
    environment:
      POKESYNC_TCP_HOST: "0.0.0.0"
      POKESYNC_TCP_PORT: 23192
      POKESYNC_REDIS_HOST: "localhost"
      POKESYNC_REDIS_PORT: 6379
    ports:
      - "23192:23192"
    depends_on:
      - "redis"
      - "db"
  db:
    image: "postgres:latest"
    ports:
    - "5432:5432"
  redis:
    image: "redis:latest"
    ports:
    - "6379:6379"